/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __knownSymbol = (name, symbol) => (symbol = Symbol[name]) ? symbol : /* @__PURE__ */ Symbol.for("Symbol." + name);
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};
var __await = function(promise, isYieldStar) {
  this[0] = promise;
  this[1] = isYieldStar;
};
var __asyncGenerator = (__this, __arguments, generator) => {
  var resume = (k, v, yes, no) => {
    try {
      var x = generator[k](v), isAwait = (v = x.value) instanceof __await, done = x.done;
      Promise.resolve(isAwait ? v[0] : v).then((y) => isAwait ? resume(k === "return" ? k : "next", v[1] ? { done: y.done, value: y.value } : y, yes, no) : yes({ value: y, done })).catch((e) => resume("throw", e, yes, no));
    } catch (e) {
      no(e);
    }
  }, method = (k) => it[k] = (x) => new Promise((yes, no) => resume(k, x, yes, no)), it = {};
  return generator = generator.apply(__this, __arguments), it[__knownSymbol("asyncIterator")] = () => it, method("next"), method("throw"), method("return"), it;
};

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ArcNotes
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/vaultTools.ts
var import_obsidian = require("obsidian");
var VaultTools = class {
  constructor(app) {
    this.app = app;
  }
  getNoteOutline(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian.TFile)) return null;
    const cache = this.app.metadataCache.getFileCache(file);
    const sections = [];
    const headingCounts = {};
    if (cache == null ? void 0 : cache.headings) {
      for (const h of cache.headings) {
        const text = h.heading;
        headingCounts[text] = (headingCounts[text] || 0) + 1;
        sections.push({
          heading: text,
          index: headingCounts[text] - 1
        });
      }
    }
    return {
      path: file.path,
      title: file.basename,
      sections,
      frontmatter: (cache == null ? void 0 : cache.frontmatter) || {}
    };
  }
  readNote(path) {
    return __async(this, null, function* () {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian.TFile)) return null;
      return yield this.app.vault.read(file);
    });
  }
  getSectionText(path, section) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!(file instanceof import_obsidian.TFile)) return null;
    const cache = this.app.metadataCache.getFileCache(file);
    if (!(cache == null ? void 0 : cache.headings)) return null;
    const header = cache.headings.filter((h) => h.heading === section.heading)[section.index];
    if (!header) return null;
    return "Section content retrieval not fully implemented but mapped.";
  }
  // Improved version of getSectionText using line offsets from metadata cache
  getSectionTextAsync(path, section) {
    return __async(this, null, function* () {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian.TFile)) return null;
      const cache = this.app.metadataCache.getFileCache(file);
      if (!(cache == null ? void 0 : cache.headings)) return null;
      const headings = cache.headings.filter((h) => h.heading === section.heading);
      const targetHeading = headings[section.index];
      if (!targetHeading) return null;
      const content = yield this.app.vault.read(file);
      const lines = content.split("\n");
      const startLine = targetHeading.position.start.line;
      const currentLevel = targetHeading.level;
      let endLine = lines.length;
      for (const h of cache.headings) {
        if (h.position.start.line > startLine && h.level <= currentLevel) {
          endLine = h.position.start.line;
          break;
        }
      }
      return lines.slice(startLine, endLine).join("\n");
    });
  }
  searchVault(query, limit = 10) {
    const files = this.app.vault.getMarkdownFiles();
    const search = (0, import_obsidian.prepareFuzzySearch)(query);
    const results = [];
    for (const file of files) {
      const result = search(file.path);
      if (result) {
        results.push({
          path: file.path,
          title: file.basename,
          snippet: `Found in ${file.path}`
          // Real snippet logic would be more involved
        });
      }
    }
    return results.slice(0, limit);
  }
  patchNoteSection(path, section, replacementMarkdown) {
    return __async(this, null, function* () {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian.TFile)) return;
      const content = yield this.app.vault.read(file);
      const lines = content.split("\n");
      const headerRegex = new RegExp(`^#+\\s+${section.heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*$`, "i");
      let foundCount = 0;
      let headerIndex = -1;
      for (let i = 0; i < lines.length; i++) {
        if (headerRegex.test(lines[i])) {
          if (foundCount === section.index) {
            headerIndex = i;
            break;
          }
          foundCount++;
        }
      }
      if (headerIndex === -1) {
        yield this.app.vault.modify(file, content + `

## ${section.heading}
${replacementMarkdown}`);
        return;
      }
      const currentHeaderLine = lines[headerIndex];
      const currentLevel = (currentHeaderLine.match(/^#+/) || [""])[0].length;
      let nextHeaderIndex = lines.findIndex((line, idx) => {
        if (idx <= headerIndex) return false;
        const match = line.match(/^#+/);
        if (!match) return false;
        return match[0].length <= currentLevel;
      });
      if (nextHeaderIndex === -1) nextHeaderIndex = lines.length;
      const newLines = [
        ...lines.slice(0, headerIndex + 1),
        replacementMarkdown,
        ...lines.slice(nextHeaderIndex)
      ];
      yield this.app.vault.modify(file, newLines.join("\n"));
    });
  }
};

// src/ai/types.ts
var GENERAL_RESPONSE_SCHEMA = {
  type: "object",
  properties: {
    action: {
      type: "string",
      enum: [
        "answer_only",
        "rewrite_selection",
        "section_review",
        "consistency_report"
      ]
    },
    answer: { type: "string" },
    rewrite: {
      type: "object",
      properties: {
        replacementMarkdown: { type: "string" }
      },
      required: ["replacementMarkdown"]
    },
    sectionReview: {
      type: "array",
      items: {
        type: "object",
        properties: {
          label: { type: "string" },
          status: { type: "string" },
          justification: { type: "string" },
          suggestedRevision: { type: "string" }
        },
        required: ["label", "status", "justification"]
      }
    },
    consistencyIssues: {
      type: "array",
      items: {
        type: "object",
        properties: {
          description: { type: "string" },
          suggestedFix: { type: "string" }
        },
        required: ["description"]
      }
    }
  },
  required: ["action"]
};

// src/ai/perplexityClient.ts
var PerplexityClient = class {
  constructor(apiKey, model = "sonar-pro") {
    this.apiKey = apiKey;
    this.model = model;
  }
  runGeneralTool(userPrompt, ctx) {
    return __async(this, null, function* () {
      const body = {
        model: this.model,
        response_format: {
          type: "json_schema",
          json_schema: {
            name: "arc_notes_general_response",
            schema: GENERAL_RESPONSE_SCHEMA
          }
        },
        messages: [
          {
            role: "system",
            content: "You are Arc Notes, an assistant working over an Obsidian vault. You must decide whether to answer, rewrite the current selection, review a section, or report consistency issues. Always respond with JSON matching the given schema and nothing else."
          },
          {
            role: "user",
            content: `User prompt: ${userPrompt}

Problem type: ${ctx.problemType}
File path: ${ctx.filePath}

` + (ctx.selection ? `Current selection:
---
${ctx.selection}
---

` : "") + (ctx.sectionHeading && ctx.sectionText ? `Section (${ctx.sectionHeading}):
---
${ctx.sectionText}
---

` : "") + (ctx.extraContext ? `Additional context from vault:
${ctx.extraContext}
` : "")
          }
        ]
      };
      const res = yield fetch("https://api.perplexity.ai/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${this.apiKey}`
        },
        body: JSON.stringify(body)
      });
      if (!res.ok) {
        const errorText = yield res.text();
        throw new Error(`Perplexity error: ${res.status} ${res.statusText} - ${errorText}`);
      }
      const json = yield res.json();
      const content = json.choices[0].message.content;
      try {
        return JSON.parse(content);
      } catch (e) {
        console.error("Failed to parse Perplexity JSON response:", content);
        throw new Error("AI returned malformed JSON. Please try again.");
      }
    });
  }
};

// src/ai/PerplexityProvider.ts
var import_obsidian2 = require("obsidian");
var PerplexityProvider = class {
  constructor(apiKey, model = "llama-3.1-sonar-large-128k-online") {
    this.name = "Perplexity";
    this.baseUrl = "https://api.perplexity.ai";
    this.apiKey = apiKey;
    this.model = model;
  }
  chat(messages, tools) {
    return __async(this, null, function* () {
      const payload = {
        model: this.model,
        messages,
        tools,
        tool_choice: tools ? "auto" : void 0,
        temperature: 0.2
      };
      console.log("[PerplexityProvider] Request:", {
        model: this.model,
        messageCount: messages.length,
        toolCount: (tools == null ? void 0 : tools.length) || 0,
        hasTools: !!tools,
        toolNames: tools == null ? void 0 : tools.map((t) => t.function.name)
      });
      console.log("[PerplexityProvider] Full payload:", JSON.stringify(payload, null, 2));
      const response = yield (0, import_obsidian2.requestUrl)({
        url: `${this.baseUrl}/chat/completions`,
        method: "POST",
        headers: {
          "Authorization": `Bearer ${this.apiKey}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify(payload)
      });
      if (response.status !== 200) {
        throw new Error(`Perplexity API error: ${response.status} ${response.text}`);
      }
      const data = response.json;
      console.log("[PerplexityProvider] Response data:", JSON.stringify(data, null, 2));
      const choice = data.choices[0];
      return {
        content: choice.message.content,
        model: this.model,
        tool_calls: choice.message.tool_calls
      };
    });
  }
  streamChat(messages, tools) {
    return __asyncGenerator(this, null, function* () {
      throw new Error("Streaming not supported with Obsidian's requestUrl");
    });
  }
};

// src/ai/OpenAIProvider.ts
var import_obsidian3 = require("obsidian");
var OpenAIProvider = class {
  constructor(apiKey, model = "gpt-4o-mini") {
    this.name = "OpenAI";
    this.baseUrl = "https://api.openai.com/v1";
    this.apiKey = apiKey;
    this.model = model;
  }
  chat(messages, tools) {
    return __async(this, null, function* () {
      var _a, _b, _c;
      const payload = {
        model: this.model,
        messages,
        tools,
        tool_choice: tools && tools.length > 0 ? "auto" : void 0,
        temperature: 0.2
      };
      console.log("[OpenAIProvider] Request:", {
        model: this.model,
        messageCount: messages.length,
        toolCount: (tools == null ? void 0 : tools.length) || 0,
        hasTools: !!tools,
        toolNames: tools == null ? void 0 : tools.map((t) => t.function.name)
      });
      let response;
      try {
        response = yield (0, import_obsidian3.requestUrl)({
          url: `${this.baseUrl}/chat/completions`,
          method: "POST",
          headers: {
            "Authorization": `Bearer ${this.apiKey}`,
            "Content-Type": "application/json"
          },
          body: JSON.stringify(payload)
        });
      } catch (error) {
        console.error("[OpenAIProvider] Request failed:", error);
        throw new Error(`OpenAI API request failed: ${error.message}`);
      }
      console.log("[OpenAIProvider] Response status:", response.status);
      if (response.status !== 200) {
        console.error("[OpenAIProvider] Error response:", response.text);
        throw new Error(`OpenAI API error: ${response.status} ${response.text}`);
      }
      const data = response.json;
      console.log("[OpenAIProvider] Response:", {
        hasChoices: !!data.choices,
        toolCallCount: ((_c = (_b = (_a = data.choices[0]) == null ? void 0 : _a.message) == null ? void 0 : _b.tool_calls) == null ? void 0 : _c.length) || 0
      });
      const choice = data.choices[0];
      return {
        content: choice.message.content,
        model: this.model,
        tool_calls: choice.message.tool_calls
      };
    });
  }
};

// src/ai/AnthropicProvider.ts
var import_obsidian4 = require("obsidian");
var AnthropicProvider = class {
  constructor(apiKey, model = "claude-3-5-sonnet-20241022") {
    this.name = "Anthropic";
    this.baseUrl = "https://api.anthropic.com/v1";
    this.apiKey = apiKey;
    this.model = model;
  }
  chat(messages, tools) {
    return __async(this, null, function* () {
      var _a, _b, _c;
      const systemMessage = ((_a = messages.find((m) => m.role === "system")) == null ? void 0 : _a.content) || "";
      const conversationMessages = [];
      let pendingToolResults = [];
      console.log("[AnthropicProvider] Converting", messages.length, "messages");
      for (const m of messages.filter((m2) => m2.role !== "system")) {
        console.log("[AnthropicProvider] Processing message:", {
          role: m.role,
          hasContent: !!m.content,
          hasToolCalls: !!m.tool_calls,
          toolCallId: m.tool_call_id
        });
        if (m.role === "tool") {
          pendingToolResults.push({
            type: "tool_result",
            tool_use_id: m.tool_call_id || "",
            content: m.content || "null"
          });
        } else {
          if (pendingToolResults.length > 0) {
            conversationMessages.push({
              role: "user",
              content: pendingToolResults
            });
            pendingToolResults = [];
          }
          if (m.role === "assistant" && m.tool_calls) {
            conversationMessages.push({
              role: "assistant",
              content: [
                ...m.content ? [{ type: "text", text: m.content }] : [],
                ...m.tool_calls.map((tc) => ({
                  type: "tool_use",
                  id: tc.id,
                  name: tc.function.name,
                  input: JSON.parse(tc.function.arguments)
                }))
              ]
            });
          } else {
            conversationMessages.push({
              role: m.role,
              content: m.content || ""
            });
          }
        }
      }
      if (pendingToolResults.length > 0) {
        conversationMessages.push({
          role: "user",
          content: pendingToolResults
        });
      }
      const anthropicTools = tools == null ? void 0 : tools.map((t) => ({
        name: t.function.name,
        description: t.function.description,
        input_schema: t.function.parameters
      }));
      const payload = {
        model: this.model,
        max_tokens: 4096,
        system: systemMessage,
        messages: conversationMessages,
        tools: anthropicTools,
        temperature: 0.2
      };
      console.log("[AnthropicProvider] Request:", {
        model: this.model,
        messageCount: conversationMessages.length,
        toolCount: (anthropicTools == null ? void 0 : anthropicTools.length) || 0,
        hasTools: !!anthropicTools,
        toolNames: anthropicTools == null ? void 0 : anthropicTools.map((t) => t.name),
        lastMessageRole: (_b = conversationMessages[conversationMessages.length - 1]) == null ? void 0 : _b.role
      });
      const lastMsg = conversationMessages[conversationMessages.length - 1];
      if ((lastMsg == null ? void 0 : lastMsg.role) === "user" && Array.isArray(lastMsg.content)) {
        const hasToolResult = lastMsg.content.some((c) => c.type === "tool_result");
        if (hasToolResult) {
          console.log("[AnthropicProvider] Sending tool results:", lastMsg.content);
        }
      }
      let response;
      try {
        response = yield (0, import_obsidian4.requestUrl)({
          url: `${this.baseUrl}/messages`,
          method: "POST",
          headers: {
            "x-api-key": this.apiKey,
            "anthropic-version": "2023-06-01",
            "Content-Type": "application/json"
          },
          body: JSON.stringify(payload)
        });
      } catch (error) {
        console.error("[AnthropicProvider] Request failed:", error);
        console.error("[AnthropicProvider] Failed payload:", JSON.stringify(payload, null, 2));
        throw new Error(`Anthropic API request failed: ${error.message}`);
      }
      console.log("[AnthropicProvider] Response status:", response.status);
      if (response.status !== 200) {
        console.error("[AnthropicProvider] Error response:", response.text);
        console.error("[AnthropicProvider] Request payload was:", JSON.stringify(payload, null, 2));
        throw new Error(`Anthropic API error: ${response.status} - ${response.text}`);
      }
      const data = response.json;
      console.log("[AnthropicProvider] Response:", {
        stopReason: data.stop_reason,
        contentBlocks: ((_c = data.content) == null ? void 0 : _c.length) || 0
      });
      let textContent = "";
      const toolCalls = [];
      for (const block of data.content || []) {
        if (block.type === "text") {
          textContent += block.text;
        } else if (block.type === "tool_use") {
          toolCalls.push({
            id: block.id,
            type: "function",
            function: {
              name: block.name,
              arguments: JSON.stringify(block.input)
            }
          });
        }
      }
      return {
        content: textContent || null,
        model: this.model,
        tool_calls: toolCalls.length > 0 ? toolCalls : void 0
      };
    });
  }
};

// src/ai/ToolExecutor.ts
var ToolExecutor = class {
  constructor(vaultManager) {
    this.vaultManager = vaultManager;
  }
  executeToolCalls(toolCalls) {
    return __async(this, null, function* () {
      const results = [];
      for (const toolCall of toolCalls) {
        try {
          const result = yield this.executeSingleTool(toolCall);
          results.push({
            tool_call_id: toolCall.id,
            name: toolCall.function.name,
            content: JSON.stringify(result)
          });
        } catch (error) {
          results.push({
            tool_call_id: toolCall.id,
            name: toolCall.function.name,
            content: JSON.stringify({
              error: error.message,
              success: false
            })
          });
        }
      }
      return results;
    });
  }
  executeSingleTool(toolCall) {
    return __async(this, null, function* () {
      const { name, arguments: argsStr } = toolCall.function;
      const args = JSON.parse(argsStr);
      switch (name) {
        case "search_vault":
          return yield this.vaultManager.searchVault(args.query);
        case "read_file":
          return yield this.vaultManager.readFile(args.path);
        case "get_note_outline":
          return yield this.vaultManager.getNoteOutline(args.path);
        case "read_neighbor_notes":
          return yield this.vaultManager.readNeighborNotes(args.path);
        case "patch_note_section":
          const success = yield this.vaultManager.patchSection(
            args.path,
            args.section,
            args.content
          );
          return { success, path: args.path, section: args.section };
        default:
          throw new Error(`Unknown tool: ${name}`);
      }
    });
  }
};

// src/vault/VaultManager.ts
var import_obsidian5 = require("obsidian");
var VaultManager = class {
  constructor(app) {
    this.app = app;
  }
  /**
   * Searches the vault for a query and returns relevant file paths.
   */
  searchVault(query) {
    return __async(this, null, function* () {
      const files = this.app.vault.getMarkdownFiles();
      const search = (0, import_obsidian5.prepareFuzzySearch)(query);
      const results = [];
      for (const file of files) {
        const result = search(file.path);
        if (result) {
          results.push({
            path: file.path,
            score: result.score
          });
        }
      }
      return results.sort((a, b) => b.score - a.score).slice(0, 10);
    });
  }
  /**
   * Reads the full content of a file.
   */
  readFile(path) {
    return __async(this, null, function* () {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (file instanceof import_obsidian5.TFile) {
        return yield this.app.vault.read(file);
      }
      return null;
    });
  }
  /**
   * Returns the structure of a note (headings and frontmatter).
   */
  getNoteOutline(path) {
    return __async(this, null, function* () {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian5.TFile)) return null;
      const cache = this.app.metadataCache.getFileCache(file);
      const sections = [];
      const headingCounts = {};
      if (cache == null ? void 0 : cache.headings) {
        for (const h of cache.headings) {
          const text = h.heading;
          headingCounts[text] = (headingCounts[text] || 0) + 1;
          sections.push({
            heading: text,
            index: headingCounts[text] - 1
          });
        }
      }
      return {
        title: file.basename,
        sections,
        frontmatter: (cache == null ? void 0 : cache.frontmatter) || {}
      };
    });
  }
  /**
   * Finds notes linked to or from the target path.
   */
  readNeighborNotes(path) {
    return __async(this, null, function* () {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian5.TFile)) return [];
      const neighbors = /* @__PURE__ */ new Set();
      const cache = this.app.metadataCache.getFileCache(file);
      if (cache == null ? void 0 : cache.links) {
        cache.links.forEach((l) => neighbors.add(l.link));
      }
      const resolvedLinks = this.app.metadataCache.resolvedLinks;
      for (const [sourcePath, links] of Object.entries(resolvedLinks)) {
        if (links[file.path]) {
          neighbors.add(sourcePath);
        }
      }
      const results = [];
      for (const nPath of Array.from(neighbors).slice(0, 5)) {
        const nFile = this.app.vault.getAbstractFileByPath(nPath);
        if (nFile instanceof import_obsidian5.TFile) {
          const content = yield this.app.vault.read(nFile);
          results.push({
            path: nPath,
            snippet: content.slice(0, 200) + "..."
          });
        }
      }
      return results;
    });
  }
  /**
   * Patches or appends content to a specific section identified by Header + Index.
   */
  patchSection(path, section, content) {
    return __async(this, null, function* () {
      const file = this.app.vault.getAbstractFileByPath(path);
      if (!(file instanceof import_obsidian5.TFile)) return false;
      const fileContent = yield this.app.vault.read(file);
      const lines = fileContent.split("\n");
      const headerRegex = new RegExp(`^#+\\s+${section.heading.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*$`, "i");
      let foundCount = 0;
      let headerIndex = -1;
      for (let i = 0; i < lines.length; i++) {
        if (headerRegex.test(lines[i])) {
          if (foundCount === section.index) {
            headerIndex = i;
            break;
          }
          foundCount++;
        }
      }
      if (headerIndex === -1) {
        yield this.app.vault.modify(file, fileContent + `

## ${section.heading}
${content}`);
        return true;
      }
      const currentHeaderLine = lines[headerIndex];
      const currentLevel = (currentHeaderLine.match(/^#+/) || [""])[0].length;
      let nextHeaderIndex = lines.findIndex((line, idx) => {
        if (idx <= headerIndex) return false;
        const match = line.match(/^#+/);
        if (!match) return false;
        return match[0].length <= currentLevel;
      });
      if (nextHeaderIndex === -1) nextHeaderIndex = lines.length;
      const newLines = [
        ...lines.slice(0, headerIndex + 1),
        content,
        ...lines.slice(nextHeaderIndex)
      ];
      yield this.app.vault.modify(file, newLines.join("\n"));
      return true;
    });
  }
};
var VAULT_TOOLS = [
  {
    type: "function",
    function: {
      name: "search_vault",
      description: "Search for notes in the vault by keywords or fuzzy matching. Returns a list of file paths.",
      parameters: {
        type: "object",
        properties: {
          query: { type: "string", description: "The search query." }
        },
        required: ["query"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "read_file",
      description: "Read the full contents of a note by its path.",
      parameters: {
        type: "object",
        properties: {
          path: { type: "string", description: "The absolute path of the file." }
        },
        required: ["path"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "get_note_outline",
      description: "Get the list of headings and frontmatter for a note. Use this to find specific sections to patch.",
      parameters: {
        type: "object",
        properties: {
          path: { type: "string", description: "Path to the file." }
        },
        required: ["path"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "read_neighbor_notes",
      description: "Find notes that are linked to or from a given note. Useful for cross-referencing consistency.",
      parameters: {
        type: "object",
        properties: {
          path: { type: "string", description: "Path to the file." }
        },
        required: ["path"]
      }
    }
  },
  {
    type: "function",
    function: {
      name: "patch_note_section",
      description: "Update or append content to a specific section in a note identified by heading and index.",
      parameters: {
        type: "object",
        properties: {
          path: { type: "string", description: "Path to the file." },
          section: {
            type: "object",
            properties: {
              heading: { type: "string" },
              index: { type: "integer" }
            },
            required: ["heading", "index"]
          },
          content: { type: "string", description: "The new markdown content." }
        },
        required: ["path", "section", "content"]
      }
    }
  }
];

// src/ui/ChatView.ts
var import_obsidian6 = require("obsidian");
var CHAT_VIEW_TYPE = "arc-notes-chat-view";
var ChatView = class extends import_obsidian6.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentContext = null;
    this.conversationHistory = [];
    this.plugin = plugin;
  }
  setContext(ctx) {
    this.currentContext = ctx;
    this.addSystemMessage(`Context loaded: [${ctx.path}] ${ctx.selection ? "(Selection detected)" : ""}`);
  }
  getViewType() {
    return CHAT_VIEW_TYPE;
  }
  getDisplayText() {
    return "Arc Notes Chat";
  }
  getIcon() {
    return "message-square";
  }
  onOpen() {
    return __async(this, null, function* () {
      const container = this.containerEl.children[1];
      container.empty();
      container.addClass("arc-notes-chat-view");
      this.chatContainer = container.createDiv({ cls: "arc-notes-chat-container" });
      this.messagesContainer = this.chatContainer.createDiv({
        cls: "arc-notes-messages"
      });
      this.inputContainer = this.chatContainer.createDiv({
        cls: "arc-notes-input-container"
      });
      const inputWrapper = this.inputContainer.createDiv({
        cls: "arc-notes-input-wrapper"
      });
      const textarea = inputWrapper.createEl("textarea", {
        cls: "arc-notes-input",
        attr: {
          placeholder: "Ask Arc Notes...",
          rows: "1"
        }
      });
      const sendButton = inputWrapper.createEl("button", {
        cls: "arc-notes-send-button",
        text: "\u2191"
      });
      textarea.addEventListener("input", () => {
        textarea.style.height = "auto";
        textarea.style.height = textarea.scrollHeight + "px";
      });
      const sendMessage = () => __async(this, null, function* () {
        const message = textarea.value.trim();
        if (!message) return;
        textarea.value = "";
        textarea.style.height = "auto";
        yield this.handleUserMessage(message);
      });
      sendButton.addEventListener("click", sendMessage);
      textarea.addEventListener("keydown", (e) => {
        if (e.key === "Enter" && !e.shiftKey) {
          e.preventDefault();
          sendMessage();
        }
      });
      yield this.addSystemMessage("Arc Notes initialized. Ready for orchestration.");
    });
  }
  onClose() {
    return __async(this, null, function* () {
    });
  }
  addUserMessage(content) {
    return __async(this, null, function* () {
      this.conversationHistory.push({ role: "user", content });
      const messageEl = this.messagesContainer.createDiv({
        cls: "arc-notes-message arc-notes-user-message"
      });
      const contentEl = messageEl.createDiv({ cls: "arc-notes-message-content" });
      yield import_obsidian6.MarkdownRenderer.render(this.app, content, contentEl, "", this);
      this.scrollToBottom();
    });
  }
  addAssistantMessage(content) {
    return __async(this, null, function* () {
      this.conversationHistory.push({
        role: "assistant",
        content,
        tool_calls: void 0
      });
      const messageEl = this.messagesContainer.createDiv({
        cls: "arc-notes-message arc-notes-assistant-message"
      });
      const contentEl = messageEl.createDiv({ cls: "arc-notes-message-content" });
      yield import_obsidian6.MarkdownRenderer.render(this.app, content, contentEl, "", this);
      this.scrollToBottom();
      return contentEl;
    });
  }
  addSystemMessage(content) {
    return __async(this, null, function* () {
      const messageEl = this.messagesContainer.createDiv({
        cls: "arc-notes-message arc-notes-system-message"
      });
      const contentEl = messageEl.createDiv({ cls: "arc-notes-message-content" });
      yield import_obsidian6.MarkdownRenderer.render(this.app, content, contentEl, "", this);
      this.scrollToBottom();
    });
  }
  scrollToBottom() {
    this.messagesContainer.scrollTop = this.messagesContainer.scrollHeight;
  }
  clearHistory() {
    this.conversationHistory = [];
    this.messagesContainer.empty();
  }
  addToolResultToHistory(toolCallId, toolName, result) {
    this.conversationHistory.push({
      role: "tool",
      content: result,
      tool_call_id: toolCallId,
      name: toolName
    });
  }
  getConversationHistory() {
    return [...this.conversationHistory];
  }
  handleUserMessage(content) {
    return __async(this, null, function* () {
      yield this.addUserMessage(content);
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        if (this.currentContext && this.currentContext.path !== activeFile.path) {
          this.currentContext = { path: activeFile.path };
        } else if (!this.currentContext) {
          this.currentContext = { path: activeFile.path };
        }
      }
      if (!this.currentContext) {
        yield this.addSystemMessage("\u274C No active file detected. Please open a note first.");
        return;
      }
      try {
        yield this.plugin.handleAgenticChat(content, this.currentContext, this);
      } catch (error) {
        yield this.addSystemMessage(`\u274C Error: ${error.message}`);
      }
    });
  }
};

// src/main.ts
var DEFAULT_SETTINGS = {
  mySetting: "default",
  brainstormFolder: "Brainstorms",
  aiProvider: "anthropic",
  anthropicApiKey: "",
  anthropicModel: "claude-3-5-sonnet-20241022",
  openaiApiKey: "",
  openaiModel: "gpt-4o-mini",
  perplexityApiKey: "",
  perplexityModel: "sonar-pro"
};
var ArcNotes = class extends import_obsidian7.Plugin {
  onload() {
    return __async(this, null, function* () {
      console.log("loading Arc Notes");
      yield this.loadSettings();
      this.vaultTools = new VaultTools(this.app);
      this.vaultManager = new VaultManager(this.app);
      this.perplexity = new PerplexityClient(this.settings.perplexityApiKey, this.settings.perplexityModel);
      this.aiProvider = this.createAIProvider();
      this.toolExecutor = new ToolExecutor(this.vaultManager);
      this.registerView(
        CHAT_VIEW_TYPE,
        (leaf) => new ChatView(leaf, this)
      );
      this.addRibbonIcon("message-square", "Open Arc Notes Chat", () => __async(this, null, function* () {
        yield this.activateChatView();
      }));
      this.addStatusBarItem().setText("Arc Notes");
      this.addCommand({
        id: "arc-notes-new-brainstorm-note",
        name: "Create Brainstorm Note",
        checkCallback: (checking) => {
          const leaf = this.app.workspace.activeLeaf;
          if (leaf) {
            if (!checking) {
              this.createBrainstormNote();
            }
            return true;
          }
          return false;
        }
      });
      this.addCommand({
        id: "arc-notes-open-chat",
        name: "Open Chat",
        callback: () => __async(this, null, function* () {
          yield this.activateChatView();
        })
      });
      this.addCommand({
        id: "arc-notes-test-perplexity",
        name: "Test Perplexity Connection",
        callback: () => __async(this, null, function* () {
          yield this.testPerplexity();
        })
      });
      this.addSettingTab(new ArcNotesSettingTab(this.app, this));
      this.registerEvent(
        this.app.workspace.on("editor-menu", (menu, editor, view) => {
          const selection = editor.getSelection();
          const file = this.app.workspace.getActiveFile();
          if (selection && file) {
            menu.addItem((item) => {
              item.setTitle("Arc Notes: Ask about selection").setIcon("message-square").onClick(() => __async(this, null, function* () {
                yield this.activateChatView({ path: file.path, selection });
              }));
            });
          }
        })
      );
    });
  }
  onunload() {
    console.log("unloading Arc Notes");
  }
  createAIProvider() {
    if (this.settings.aiProvider === "anthropic") {
      return new AnthropicProvider(
        this.settings.anthropicApiKey,
        this.settings.anthropicModel
      );
    } else if (this.settings.aiProvider === "openai") {
      return new OpenAIProvider(
        this.settings.openaiApiKey,
        this.settings.openaiModel
      );
    } else {
      return new PerplexityProvider(
        this.settings.perplexityApiKey,
        this.settings.perplexityModel
      );
    }
  }
  activateChatView(ctx) {
    return __async(this, null, function* () {
      const { workspace } = this.app;
      let leaf = workspace.getLeavesOfType(CHAT_VIEW_TYPE)[0];
      if (!leaf) {
        leaf = workspace.getRightLeaf(false);
        yield leaf.setViewState({
          type: CHAT_VIEW_TYPE,
          active: true
        });
      }
      if (ctx && leaf.view instanceof ChatView) {
        leaf.view.setContext(ctx);
        if (ctx.selection) {
          yield leaf.view.handleUserMessage(`Regarding this selection: "${ctx.selection}"

`);
        }
      }
      workspace.revealLeaf(leaf);
    });
  }
  handleAgenticChat(userMessage, ctx, view) {
    return __async(this, null, function* () {
      var _a;
      const MAX_ITERATIONS = 10;
      let iterations = 0;
      const messages = view.getConversationHistory();
      const hasSystemMessage = messages.some((m) => m.role === "system");
      if (!hasSystemMessage) {
        messages.unshift({
          role: "system",
          content: this.getSystemPrompt(ctx)
        });
      }
      while (iterations < MAX_ITERATIONS) {
        iterations++;
        console.log("[Arc Notes] Calling Perplexity with", messages.length, "messages and", VAULT_TOOLS.length, "tools");
        const response = yield this.aiProvider.chat(messages, VAULT_TOOLS);
        console.log("[Arc Notes] Response:", {
          hasContent: !!response.content,
          hasToolCalls: !!response.tool_calls,
          toolCallCount: ((_a = response.tool_calls) == null ? void 0 : _a.length) || 0
        });
        const assistantMessage = {
          role: "assistant",
          content: response.content,
          tool_calls: response.tool_calls
        };
        messages.push(assistantMessage);
        if (response.content) {
          yield view.addAssistantMessage(response.content);
        }
        if (!response.tool_calls || response.tool_calls.length === 0) {
          break;
        }
        const toolResults = yield this.toolExecutor.executeToolCalls(
          response.tool_calls
        );
        for (const result of toolResults) {
          view.addToolResultToHistory(
            result.tool_call_id,
            result.name,
            result.content
          );
          messages.push({
            role: "tool",
            content: result.content,
            tool_call_id: result.tool_call_id,
            name: result.name
          });
        }
        yield view.addSystemMessage(
          `\u{1F527} Used ${toolResults.length} tool(s): ${toolResults.map((r) => r.name).join(", ")}`
        );
      }
      if (iterations >= MAX_ITERATIONS) {
        yield view.addSystemMessage("\u26A0\uFE0F Maximum iterations reached.");
      }
    });
  }
  getSystemPrompt(ctx) {
    return `You are Arc Notes, an AI assistant integrated into an Obsidian vault.

Current context:
- Active file: ${ctx.path}
${ctx.selection ? `- Selected text: "${ctx.selection}"` : ""}

IMPORTANT: You have access to tools that let you interact with the vault. You MUST use these tools to access vault content - you cannot see notes without using tools.

Available tools:
- search_vault: Search for notes by keywords (use this first to find relevant notes)
- read_file: Read the complete contents of a note by path
- get_note_outline: Get the structure (headings) of a note
- read_neighbor_notes: Find notes that are linked to/from a note
- patch_note_section: Update a specific section in a note

Guidelines:
1. ALWAYS use search_vault or read_file to access vault content before answering
2. If user asks about the current file (${ctx.path}), use read_file to read it first
3. Ask clarifying questions before making changes to notes
4. Use get_note_outline before using patch_note_section
5. Explain which tools you're using and why

Example workflow:
- User: "What's in my concept note?"
- You: Use read_file tool on ${ctx.path} to read it, then summarize the contents`;
  }
  handleChatRequest(prompt, ctx) {
    return __async(this, null, function* () {
      const lower = prompt.toLowerCase();
      let problemType = "free_chat";
      if (ctx.selection && (lower.includes("better") || lower.includes("improve"))) {
        problemType = "improve_selection";
      } else if (lower.includes("verify") || lower.includes("assumption")) {
        problemType = "verify_section";
      } else if (lower.includes("consistent") || lower.includes("continuity") || lower.includes("is this true")) {
        problemType = "check_consistency";
      }
      let sectionHeading;
      let sectionText;
      let extraContext = "";
      const activeNoteText = yield this.vaultTools.readNote(ctx.path);
      if (activeNoteText) {
        extraContext = `--- START ACTIVE FILE CONTENT: ${ctx.path} ---
${activeNoteText}
--- END ACTIVE FILE CONTENT ---

`;
      }
      if (problemType === "verify_section" || problemType === "improve_selection") {
        const outline = this.vaultTools.getNoteOutline(ctx.path);
        if (outline) {
          extraContext += `Note Outline: ${JSON.stringify(outline.sections)}
`;
        }
      }
      if (problemType === "check_consistency") {
        const hits = this.vaultTools.searchVault(prompt, 8);
        extraContext += hits.map((h) => `[Note: ${h.path}]
${h.snippet}`).join("\n\n");
      }
      const payload = {
        problemType,
        filePath: ctx.path,
        selection: ctx.selection,
        sectionHeading,
        sectionText,
        extraContext
      };
      return yield this.perplexity.runGeneralTool(prompt, payload);
    });
  }
  applyGeneralResponse(result, ctx, view) {
    return __async(this, null, function* () {
      switch (result.action) {
        case "answer_only":
          if (result.answer) yield view.addAssistantMessage(result.answer);
          break;
        case "rewrite_selection":
          if (!ctx.selection || !result.rewrite) {
            if (result.answer) yield view.addAssistantMessage(result.answer);
            return;
          }
          yield view.addAssistantMessage("Suggested rewrite generated. [Apply Button Placeholder]");
          if (result.answer) yield view.addAssistantMessage(result.answer);
          break;
        case "section_review":
          yield view.addAssistantMessage("Section review completed.");
          if (result.sectionReview) {
            let reviewText = result.sectionReview.map((r) => `- **${r.label}**: ${r.status}
  ${r.justification}`).join("\n");
            yield view.addAssistantMessage(reviewText);
          }
          break;
        case "consistency_report":
          yield view.addAssistantMessage("Consistency check completed.");
          if (result.consistencyIssues) {
            let issuesText = result.consistencyIssues.map((i) => `- ${i.description}`).join("\n");
            yield view.addAssistantMessage(issuesText);
          }
          break;
      }
    });
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
      if (this.perplexity) {
        this.perplexity = new PerplexityClient(this.settings.perplexityApiKey, this.settings.perplexityModel);
      }
      this.aiProvider = this.createAIProvider();
    });
  }
  createBrainstormNote() {
    return __async(this, null, function* () {
      var _a;
      const vault = this.app.vault;
      const workspace = this.app.workspace;
      const conceptName = yield promptForInput(
        this.app,
        "New Brainstorm Note",
        "Concept name"
      );
      if (!conceptName) {
        new import_obsidian7.Notice("Brainstorm note creation cancelled");
        return;
      }
      const fileName = `${conceptName}.md`;
      const folderPath = ((_a = this.settings.brainstormFolder) == null ? void 0 : _a.trim()) || "";
      const filePath = folderPath ? `${folderPath}/${fileName}` : fileName;
      const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
      const content = `---
concept: ${conceptName}
status: draft
tags: []
related_concepts: []
created: ${today}
---

## Core Idea

## Key Points

## Design Implications

## Implementation Notes

## Examples
`;
      if (folderPath) {
        try {
          yield vault.createFolder(folderPath).catch(() => {
          });
        } catch (e) {
          console.error(`Failed to ensure folder exists: ${folderPath}`, e);
        }
      }
      let file;
      try {
        file = yield vault.create(filePath, content);
      } catch (e) {
        new import_obsidian7.Notice(`Failed to create note: ${filePath}`);
        console.error(e);
        return;
      }
      const leaf = workspace.getLeaf(true);
      yield leaf.openFile(file);
      new import_obsidian7.Notice(`Created Brainstorm note: ${filePath}`);
    });
  }
  testPerplexity() {
    return __async(this, null, function* () {
      if (!this.settings.perplexityApiKey) {
        new import_obsidian7.Notice("Please set your Perplexity API key in settings first");
        return;
      }
      new import_obsidian7.Notice("Testing Perplexity connection...");
      try {
        const client = new PerplexityClient(this.settings.perplexityApiKey, this.settings.perplexityModel);
        const payload = {
          problemType: "free_chat",
          filePath: "test.md"
        };
        const response = yield client.runGeneralTool("Say 'Hello!'", payload);
        new import_obsidian7.Notice(`\u2713 Perplexity connected! Action: ${response.action}`);
      } catch (error) {
        new import_obsidian7.Notice(`\u2717 Perplexity error: ${error.message}`);
        console.error("Perplexity test failed:", error);
      }
    });
  }
};
var InputPromptModal = class extends import_obsidian7.Modal {
  constructor(app, promptText, onSubmit) {
    super(app);
    this.inputValue = "";
    this.promptText = promptText;
    this.onSubmit = onSubmit;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: this.promptText });
    const input = contentEl.createEl("input", { type: "text" });
    input.focus();
    input.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        event.preventDefault();
        this.close();
        this.onSubmit(input.value.trim() || null);
      }
      if (event.key === "Escape") {
        event.preventDefault();
        this.close();
        this.onSubmit(null);
      }
    });
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const okButton = buttonContainer.createEl("button", { text: "Create" });
    okButton.addEventListener("click", () => {
      this.close();
      this.onSubmit(input.value.trim() || null);
    });
    const cancelButton = buttonContainer.createEl("button", { text: "Cancel" });
    cancelButton.addEventListener("click", () => {
      this.close();
      this.onSubmit(null);
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
function promptForInput(app, title, placeholder) {
  return new Promise((resolve) => {
    const modal = new InputPromptModal(app, title, (value) => {
      resolve(value);
    });
    modal.open();
  });
}
var ArcNotesSettingTab = class extends import_obsidian7.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Arc Notes Settings" });
    containerEl.createEl("h3", { text: "AI Provider" });
    new import_obsidian7.Setting(containerEl).setName("Provider").setDesc("Choose which AI provider to use (Anthropic/OpenAI support tool calling)").addDropdown(
      (dropdown) => dropdown.addOption("anthropic", "Anthropic Claude (Recommended)").addOption("openai", "OpenAI").addOption("perplexity", "Perplexity").setValue(this.plugin.settings.aiProvider).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.aiProvider = value;
        yield this.plugin.saveSettings();
        this.display();
      }))
    );
    if (this.plugin.settings.aiProvider === "anthropic") {
      containerEl.createEl("h4", { text: "Anthropic Claude Configuration" });
      new import_obsidian7.Setting(containerEl).setName("Anthropic API Key").setDesc("Your Anthropic API key from https://console.anthropic.com/settings/keys").addText(
        (text) => text.setPlaceholder("sk-ant-api03-...").setValue(this.plugin.settings.anthropicApiKey || "").onChange((value) => __async(this, null, function* () {
          this.plugin.settings.anthropicApiKey = value.trim();
          yield this.plugin.saveSettings();
        }))
      );
      new import_obsidian7.Setting(containerEl).setName("Claude Model").setDesc("Choose the Claude model to use").addDropdown(
        (dropdown) => dropdown.addOption("claude-3-5-sonnet-20241022", "Claude 3.5 Sonnet (Recommended)").addOption("claude-3-5-haiku-20241022", "Claude 3.5 Haiku (Fast & Cheap)").addOption("claude-3-opus-20240229", "Claude 3 Opus (Most Capable)").setValue(this.plugin.settings.anthropicModel).onChange((value) => __async(this, null, function* () {
          this.plugin.settings.anthropicModel = value;
          yield this.plugin.saveSettings();
        }))
      );
    }
    if (this.plugin.settings.aiProvider === "openai") {
      containerEl.createEl("h4", { text: "OpenAI Configuration" });
      new import_obsidian7.Setting(containerEl).setName("OpenAI API Key").setDesc("Your OpenAI API key from https://platform.openai.com/api-keys").addText(
        (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey || "").onChange((value) => __async(this, null, function* () {
          this.plugin.settings.openaiApiKey = value.trim();
          yield this.plugin.saveSettings();
        }))
      );
      new import_obsidian7.Setting(containerEl).setName("OpenAI Model").setDesc("Choose the OpenAI model to use").addDropdown(
        (dropdown) => dropdown.addOption("gpt-4o-mini", "GPT-4o Mini (Fast & Cheap)").addOption("gpt-4o", "GPT-4o (Most Capable)").addOption("gpt-4-turbo", "GPT-4 Turbo").setValue(this.plugin.settings.openaiModel).onChange((value) => __async(this, null, function* () {
          this.plugin.settings.openaiModel = value;
          yield this.plugin.saveSettings();
        }))
      );
    }
    if (this.plugin.settings.aiProvider === "perplexity") {
      containerEl.createEl("h4", { text: "Perplexity Configuration" });
      containerEl.createEl("p", {
        text: "\u26A0\uFE0F Note: Perplexity models do not support tool calling. Chat will work but cannot access vault files.",
        cls: "setting-item-description"
      });
      new import_obsidian7.Setting(containerEl).setName("Perplexity API Key").setDesc("Your Perplexity API key from https://www.perplexity.ai/settings/api").addText(
        (text) => text.setPlaceholder("pplx-...").setValue(this.plugin.settings.perplexityApiKey || "").onChange((value) => __async(this, null, function* () {
          this.plugin.settings.perplexityApiKey = value.trim();
          yield this.plugin.saveSettings();
        }))
      );
      new import_obsidian7.Setting(containerEl).setName("Perplexity Model").setDesc("Choose the Perplexity model to use").addDropdown(
        (dropdown) => dropdown.addOption("sonar", "Sonar (Fast & Cheap)").addOption("sonar-pro", "Sonar Pro (Higher Quality)").addOption("sonar-reasoning-pro", "Sonar Reasoning Pro (With Traces)").addOption("sonar-deep-research", "Sonar Deep Research (Long-form)").setValue(this.plugin.settings.perplexityModel).onChange((value) => __async(this, null, function* () {
          this.plugin.settings.perplexityModel = value;
          yield this.plugin.saveSettings();
        }))
      );
    }
    containerEl.createEl("h3", { text: "Templates" });
    new import_obsidian7.Setting(containerEl).setName("Brainstorm folder").setDesc("Folder where Brainstorm notes will be created (e.g. Concepts/Brainstorms). Leave empty for vault root.").addText(
      (text) => text.setPlaceholder("Brainstorms").setValue(this.plugin.settings.brainstormFolder || "").onChange((value) => __async(this, null, function* () {
        this.plugin.settings.brainstormFolder = value.trim();
        yield this.plugin.saveSettings();
      }))
    );
  }
};
