# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        # Exclude the compiled main.js file as it's generated code
        # and will contain duplicates of any placeholders from main.ts.
        exclude: main.js
